LLVM_GIT ?= "git://github.com/llvm-mirror"
LLVM_GIT_PROTOCOL ?= "git"

#
# Uncomment below to enable master version of clang/llvm
#

PV = "3.9.0"
BRANCH = "release_39"
#SRCREV_llvm = "3aa4a350b49916c74f3e9bf7ff5a8f61b9937ab2"
SRCREV_clang = "07307f95d5c82d453cdc5c23f9ccd53d5ff75426"
SRCREV_llvm = "fbbabf3203c01be7bf5fe904be52aa16f2abf895"

LLVMMD5SUM = "b99eb43c934ceebecab85c6b9b1a08be"
CLANGMD5SUM = "a77eac638a3aae44a2d604217d6f0f01"
