#!/bin/sh
#

XSERVER=/usr/bin/Xorg

. /etc/profile

ARGS=" -br -pn"

if lspci  | grep VGA | grep -q Intel
then
	ARGS="$ARGS -config xorg.conf.intel"
fi

DISPLAY=':0'

exec xinit /etc/X11/Xsession -- $XSERVER $DISPLAY $ARGS $*
